table SS_D_Unidades_saude
	lineageTag: de047345-63cf-4b1c-b11d-8d1687677fb8

	column ID
		dataType: string
		lineageTag: 13e7c17f-e4cd-4769-af24-66e6fc0caa0c
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column BAIRRO
		dataType: string
		lineageTag: af65577f-9b9c-4e98-b721-cbfdcd87e893
		summarizeBy: none
		sourceColumn: BAIRRO

		annotation SummarizationSetBy = Automatic

	column CEP
		dataType: string
		lineageTag: c58b1bc3-6b85-4316-8e5b-05fdf9f3fa18
		summarizeBy: none
		sourceColumn: CEP

		annotation SummarizationSetBy = Automatic

	column CLASSIFICACAO_CNES_ID
		dataType: int64
		formatString: 0
		lineageTag: ed20106b-f462-4d48-b3da-287310035ae3
		summarizeBy: count
		sourceColumn: CLASSIFICACAO_CNES_ID

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 14f20cdf-949d-4236-8da3-b48e2f3ef187
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Unidade'
		dataType: string
		lineageTag: ab92ffd6-ac87-4eb0-9fd8-d90a0ce41040
		summarizeBy: none
		sourceColumn: Tipo de Unidade

		annotation SummarizationSetBy = Automatic

	column CLASSIFICACAO_RISCO_ESCUTA_INICIAL
		dataType: int64
		formatString: 0
		lineageTag: a2c3f7dd-f8d1-4ccc-9634-fe9bf6f704c5
		summarizeBy: sum
		sourceColumn: CLASSIFICACAO_RISCO_ESCUTA_INICIAL

		annotation SummarizationSetBy = Automatic

	column CLIENT_NAME
		dataType: string
		lineageTag: e0223069-dfac-42bc-8da7-e8cd18685211
		summarizeBy: none
		sourceColumn: CLIENT_NAME

		annotation SummarizationSetBy = Automatic

	column CODIGO_CNES
		dataType: string
		lineageTag: ce141e09-8d19-4792-99ef-10b6b903b323
		summarizeBy: none
		sourceColumn: CODIGO_CNES

		annotation SummarizationSetBy = Automatic

	column CREATED_AT
		dataType: dateTime
		formatString: General Date
		lineageTag: da04bfb4-8281-4c2a-b223-f203acaf49e9
		summarizeBy: none
		sourceColumn: CREATED_AT

		variation Variation
			isDefault
			relationship: cfe2f7a4-e74b-4cd0-9029-700cebe37ad9
			defaultHierarchy: LocalDateTable_d055a66c-7a1f-4595-b434-265614e4b08a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column EMERGENCIA
		dataType: string
		lineageTag: 09c63ff2-b5f2-4056-b89f-ba645ff21a0c
		summarizeBy: none
		sourceColumn: EMERGENCIA

		annotation SummarizationSetBy = Automatic

	column ESTADO_ID
		dataType: int64
		formatString: 0
		lineageTag: 9cb428a7-9fa7-4bc6-8aae-a221d70c97be
		summarizeBy: count
		sourceColumn: ESTADO_ID

		annotation SummarizationSetBy = Automatic

	column EXPORTACAO_ESUS
		dataType: string
		lineageTag: 22cdc989-b5dd-4adc-a8cc-319946258f2d
		summarizeBy: none
		sourceColumn: EXPORTACAO_ESUS

		annotation SummarizationSetBy = Automatic

	column LANCAMENTO_BPA_AUTOMATICO
		dataType: string
		lineageTag: 0210bb12-c9d2-4207-ac43-be5c49e0e819
		summarizeBy: none
		sourceColumn: LANCAMENTO_BPA_AUTOMATICO

		annotation SummarizationSetBy = Automatic

	column LOGRADOURO
		dataType: string
		lineageTag: b5ed1f5b-9da0-489c-8d3a-aebc06c2f48b
		summarizeBy: none
		sourceColumn: LOGRADOURO

		annotation SummarizationSetBy = Automatic

	column MUNICIPIO_ID
		dataType: int64
		formatString: 0
		lineageTag: 03523dc1-d2bf-4fdf-b1ad-7fc729ab26fa
		summarizeBy: count
		sourceColumn: MUNICIPIO_ID

		annotation SummarizationSetBy = Automatic

	column NUMERO
		dataType: string
		lineageTag: 4ca6be94-e540-47b5-ba8e-0cdc6ebd8a31
		summarizeBy: none
		sourceColumn: NUMERO

		annotation SummarizationSetBy = Automatic

	column SITUACAO_UNIDADE_SAUDE_ID
		dataType: int64
		formatString: 0
		lineageTag: 6d5fca85-2fdc-4e7f-b4bf-9e160d160b4d
		summarizeBy: count
		sourceColumn: SITUACAO_UNIDADE_SAUDE_ID

		annotation SummarizationSetBy = Automatic

	column STATUS
		dataType: string
		lineageTag: 4d9b6a55-d8a2-4bd6-b1d5-5df01d391944
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column TIPO_UNIDADE_ID
		dataType: int64
		formatString: 0
		lineageTag: c8a39a33-2fcf-4107-a05d-b5ccec1ce144
		summarizeBy: count
		sourceColumn: TIPO_UNIDADE_ID

		annotation SummarizationSetBy = Automatic

	column UNIDADE_SAUDE_ID
		dataType: int64
		formatString: 0
		lineageTag: 8663158b-aa1f-4159-b81c-771783b65b80
		summarizeBy: count
		sourceColumn: UNIDADE_SAUDE_ID

		annotation SummarizationSetBy = Automatic

	column UPDATED_AT
		dataType: dateTime
		formatString: General Date
		lineageTag: ff2f5934-61bb-4df5-96af-2e299f9a5942
		summarizeBy: none
		sourceColumn: UPDATED_AT

		variation Variation
			isDefault
			relationship: 866717d0-29eb-474e-93d4-a7613fe59d3f
			defaultHierarchy: LocalDateTable_89afa4f2-5e53-473f-a50a-93b6ba84826d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: 5b4d3d58-0708-4107-9469-cf18448b773e
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	column TIMESTAMP_ORIGIN
		dataType: string
		lineageTag: 97a41a40-ca2a-4fe3-a037-333a57606ead
		summarizeBy: none
		sourceColumn: TIMESTAMP_ORIGIN

		annotation SummarizationSetBy = Automatic

	column FILENAME_ORIGIN
		dataType: string
		lineageTag: bbf662c7-5a68-4252-9ddc-c342a64ee4ac
		summarizeBy: none
		sourceColumn: FILENAME_ORIGIN

		annotation SummarizationSetBy = Automatic

	partition SS_D_Unidades_saude = m
		mode: import
		source =
				let
				  Origem = PostgreSQL.Database("om30-dl.d4all.com.br:55113", "postgres"),
				    dlv_saude_prd_ss_d_unidades_saude = Origem{[Schema="dlv_saude_prd",Item="ss_d_unidades_saude"]}[Data],
				    #"Texto em Maiúscula" = Table.TransformColumns(dlv_saude_prd_ss_d_unidades_saude,{{"NOME", Text.Upper, type text}}),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Texto em Maiúscula",{"ID", "ACOMPANHANTE_PA_OBRIGATORIO", "ADERIU_PROGRAMA_UNIDADE_FILANTROPICA", "AGENDA_ESPECIFICA_COMPLEMENTAR", "AGENDA_REGULADA", "APONTAMENTO_ATENDIMENTO_PA_ABERTO", "APONTAMENTO_CONDUTA_FINAL", "ATENDIMENTO_PA_ESPECIALIDADE_IDADE", "ATIVIDADE_ID", "AUSENTES_UNIFICADA_ACOLHIMENTO", "AUSENTES_UNIFICADA_ATENDIMENTO", "BAIRRO", "BLOCOS_EXPANDIDOS_ESCUTA_ATENDIMENTOS", "BLOQUEAR_AGENDAMENTO_DUPLICADO", "CENTRO_CUSTO_ORIGEM_PRINCIPAL_ID", "CEP", "CLASSIFICACAO_CNES_ID", "NOME", "CLASSIFICACAO_RISCO_ESCUTA_INICIAL", "CLIENTELA_ID", "CLIENT_NAME", "CNES_INVALIDO", "CNPJ_NUMERO", "CODIGO", "CODIGO_CNES", "CODIGO_DISTRITO_ADMINISTRATIVO", "CODIGO_DISTRITO_SANITARIO", "CODIGO_MICRO_REGIAO_SAUDE", "CODIGO_REGIAO_SAUDE", "COMPLEMENTO", "COMPROVANTE_AGENDAMENTO_IMPRESSORA_ZEBRA", "CONGELAR_BLOCO_INFO_MUNICIPE", "CONSULTA_UNIDADES", "CONTRATOS_TCEP_EXPIRADOS", "COTAS_REGULACAO", "CPF_NUMERO", "CREATED_AT", "DATA_ATUALIZACAO_COORDENADAS", "DATA_AUTOMATICA_ATESTADO", "DATA_AUTOMATICA_RECEITUARIO_INICIO", "DATA_AVALIACAO_PNASS", "DATA_CREDITACAO", "DATA_EXPEDICAO_ALVARA", "DATA_FECHAMENTO", "DECLARACAO_HORA_AUTOMATICA", "DESCRICAO_SUBTIPO_UNIDADE_ID", "DIAS_AGENDAMENTO", "DIRETOR_CLINICO_ID", "EMAIL", "EMERGENCIA", "ESCOLHE_ORIGEM_REGULACAO", "ESPECIALIDADE_APOS_ACOLHIMENTO_PA", "ESTADO_ID", "ESTOQUE_VACINACAO_DESATIVADO", "EXIBE_APENAS_SIGTAP", "EXIBE_SALDO_ESTOQUE", "EXPORTACAO_ESUS", "FATURAMENTO_REGISTRO_PROCEDIMENTO_ID", "FAX", "GERAR_PRONTUARIO_SEQUECIAL", "GERENCIAMENTO_FILAS", "GESTAO_LEITOS", "HABILITAR_FICHAS_ESUS_ATENDIMENTO_DOMICILIAR", "HABILITAR_TEMPO_CHAMADA", "HISTORICO_ATENDIMENTOPA_ABERTO", "HISTORICO_CONDUTA_FINAL", "IMPRESSAO_RECEITUARIO", "IMPRIMIR_ETIQUETA", "INATIVA", "INDICADOR_PREVINE_BRASIL", "JUSTIFICATIVA_AUSENCIA_AGENDAMENTO", "LANCAMENTO_BPA_AUTOMATICO", "LATITUDE", "LAUDO_APAC", "LIBERACAO_CRITICA_0356", "LOCAL_ID", "LOGRADOURO", "LONGITUDE", "MANTENEDORA_ID", "MODELO_FICHA_ATENDIMENTO_PA_ID", "MODELO_PRONTUARIO_ATENCAO_BASICA", "MONITORAMENTO_CEO", "MOTIVO_DESABILITACAO_UNIDADE_ID", "MUNICIPIO_ID", "NIVEL_HIERARQUIA_ID", "NOME_USUARIO_INTERNO", "NOTIFCANTE", "NUMERO", "NUMERO_ALVARA", "OBRIGATORIEDADE_CID", "OBRIGATORIEDADE_JUSTIFICATIVA_GUIA_SADT", "OBRIGATORIO_CIAP_E_CID", "OCULTAR_ABAS_FATURAMENTO_BPA", "OCULTAR_ABA_FICHA_ESUS", "OCULTAR_CODIGO_DE_BARRAS", "ODONTOGRAMA", "ORGAO_EXPEDIDOR_ALVARA_ID", "PAGINACAO_REQUISICOES_ESTOQUE", "PAINEL_SENHA", "PERMITE_LANCAMENTO_INFORMATIVO_BPA", "POSSUI_ACOLHIMENTO", "POSSUI_PRONTUARIO", "PROCEDIMENTO_OBRIGATORIO_AGENDA", "PRONTUARIO_DIGITALIZADO", "QUANTIDADE_SALAS", "RAZAO_SOCIAL", "REGISTRO_DIRETOR_CLINICO", "REMOCAO_HORARIO_RETROATIVO", "REQUISICAO_TRANSFERENCIA_AREA_ABRANGENCIA", "REQUISICAO_TRANSFERENCIA_GRUPO_SEGMENTO", "RETENCAO_TRIBUTARIA_ID", "SALVA_FICHAS_ESUS_AUTOMATICAMENTE", "SITUACAO_UNIDADE_SAUDE_ID", "STATUS", "STATUS_AVALIACAO_PNASS", "STATUS_CONTRATO_SUS", "STATUS_INTERNO", "TELEFONE", "TEMPO_CHAMADA", "TIPO_AGENDAMENTO_ID", "TIPO_ATESTADO_ID", "TIPO_AVALIACAO", "TIPO_CLASSE_AVALIACAO", "TIPO_ESFERA_ID", "TIPO_LOGRADOURO_ID", "TIPO_NATUREZA_JURIDICA_ID", "TIPO_NATUREZA_ORGANIZACAO_ID", "TIPO_PESSOA_CNES_ID", "TIPO_PRESTADOR_ID", "TIPO_RECEITUARIO_ID", "TIPO_SEPARACAO_REQUISICAO_CONSUMO_ID", "TIPO_TERCEIRO_SIH", "TIPO_UNIDADE_ID", "TIPO_UNIESP", "TIPO_VALIDACAO_AGENDAMENTO_ID", "TIPO_VALIDACAO_TRIAGEM", "TIPO_VINCULO_SUS", "TOKEN_PAINEL_SENHA", "TURNO_ATENDIMENTO_ID", "ULTIMA_ATUALIZACAO", "UNIDADE_SAUDE_ID", "UNIFICACAO_CONSULTA_PRONTUARIO", "UNIFICA_FICHA_ATENDIMENTO", "UPDATED_AT", "URGENCIA", "URL", "USUARIO_ATUALIZACAO_COORDENADAS", "USUARIO_ULTIMA_ATUALIZACAO", "UUID", "VALIDACAO_CAMPO_AFERICAO", "VALIDACAO_MUNICIPE", "VERIFICA_FILA_ESPERA_AGENDAMENTO", "VISUALIZAR_LISTA_AUSENTES_POR_CBO", "TIMESTAMP_ORIGIN", "FILENAME_ORIGIN"}),
				    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Colunas Reordenadas", "Base tipo", each Text.BeforeDelimiter(Text.Proper([NOME]), " "), type text),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Texto Inserido Antes do Delimitador", "Personalizar", each if [CLASSIFICACAO_CNES_ID] = 2 then "Atenção Primária" else if [CLASSIFICACAO_CNES_ID] = 16 then "Vigilância em Saúde" else if [CLASSIFICACAO_CNES_ID] = 27 then "Urgência e Emergência" else if [CLASSIFICACAO_CNES_ID] = 11 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 3 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 7 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 24 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 15 then "Farmácia" else if [CLASSIFICACAO_CNES_ID] = 14 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 12 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 9 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 34 then "Vigilância em Saúde" else if [CLASSIFICACAO_CNES_ID] = 4 then "Atenção Especializada" else if [CLASSIFICACAO_CNES_ID] = 22 then "Secretaria de Saúde" else if [CLASSIFICACAO_CNES_ID] = 28 then "Atenção Especializada" else "Sem classificação", type text),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Condicional Adicionada",{{"Personalizar", "Tipo de Unidade"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"CLASSIFICACAO_CNES_ID", Int64.Type}}),
				    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Tipo Alterado",{"ID", "ACOMPANHANTE_PA_OBRIGATORIO", "ADERIU_PROGRAMA_UNIDADE_FILANTROPICA", "AGENDA_ESPECIFICA_COMPLEMENTAR", "AGENDA_REGULADA", "APONTAMENTO_ATENDIMENTO_PA_ABERTO", "APONTAMENTO_CONDUTA_FINAL", "ATENDIMENTO_PA_ESPECIALIDADE_IDADE", "ATIVIDADE_ID", "AUSENTES_UNIFICADA_ACOLHIMENTO", "AUSENTES_UNIFICADA_ATENDIMENTO", "BAIRRO", "BLOCOS_EXPANDIDOS_ESCUTA_ATENDIMENTOS", "BLOQUEAR_AGENDAMENTO_DUPLICADO", "CENTRO_CUSTO_ORIGEM_PRINCIPAL_ID", "CEP", "CLASSIFICACAO_CNES_ID", "NOME", "Tipo de Unidade", "CLASSIFICACAO_RISCO_ESCUTA_INICIAL", "CLIENTELA_ID", "CLIENT_NAME", "CNES_INVALIDO", "CNPJ_NUMERO", "CODIGO", "CODIGO_CNES", "CODIGO_DISTRITO_ADMINISTRATIVO", "CODIGO_DISTRITO_SANITARIO", "CODIGO_MICRO_REGIAO_SAUDE", "CODIGO_REGIAO_SAUDE", "COMPLEMENTO", "COMPROVANTE_AGENDAMENTO_IMPRESSORA_ZEBRA", "CONGELAR_BLOCO_INFO_MUNICIPE", "CONSULTA_UNIDADES", "CONTRATOS_TCEP_EXPIRADOS", "COTAS_REGULACAO", "CPF_NUMERO", "CREATED_AT", "DATA_ATUALIZACAO_COORDENADAS", "DATA_AUTOMATICA_ATESTADO", "DATA_AUTOMATICA_RECEITUARIO_INICIO", "DATA_AVALIACAO_PNASS", "DATA_CREDITACAO", "DATA_EXPEDICAO_ALVARA", "DATA_FECHAMENTO", "DECLARACAO_HORA_AUTOMATICA", "DESCRICAO_SUBTIPO_UNIDADE_ID", "DIAS_AGENDAMENTO", "DIRETOR_CLINICO_ID", "EMAIL", "EMERGENCIA", "ESCOLHE_ORIGEM_REGULACAO", "ESPECIALIDADE_APOS_ACOLHIMENTO_PA", "ESTADO_ID", "ESTOQUE_VACINACAO_DESATIVADO", "EXIBE_APENAS_SIGTAP", "EXIBE_SALDO_ESTOQUE", "EXPORTACAO_ESUS", "FATURAMENTO_REGISTRO_PROCEDIMENTO_ID", "FAX", "GERAR_PRONTUARIO_SEQUECIAL", "GERENCIAMENTO_FILAS", "GESTAO_LEITOS", "HABILITAR_FICHAS_ESUS_ATENDIMENTO_DOMICILIAR", "HABILITAR_TEMPO_CHAMADA", "HISTORICO_ATENDIMENTOPA_ABERTO", "HISTORICO_CONDUTA_FINAL", "IMPRESSAO_RECEITUARIO", "IMPRIMIR_ETIQUETA", "INATIVA", "INDICADOR_PREVINE_BRASIL", "JUSTIFICATIVA_AUSENCIA_AGENDAMENTO", "LANCAMENTO_BPA_AUTOMATICO", "LATITUDE", "LAUDO_APAC", "LIBERACAO_CRITICA_0356", "LOCAL_ID", "LOGRADOURO", "LONGITUDE", "MANTENEDORA_ID", "MODELO_FICHA_ATENDIMENTO_PA_ID", "MODELO_PRONTUARIO_ATENCAO_BASICA", "MONITORAMENTO_CEO", "MOTIVO_DESABILITACAO_UNIDADE_ID", "MUNICIPIO_ID", "NIVEL_HIERARQUIA_ID", "NOME_USUARIO_INTERNO", "NOTIFCANTE", "NUMERO", "NUMERO_ALVARA", "OBRIGATORIEDADE_CID", "OBRIGATORIEDADE_JUSTIFICATIVA_GUIA_SADT", "OBRIGATORIO_CIAP_E_CID", "OCULTAR_ABAS_FATURAMENTO_BPA", "OCULTAR_ABA_FICHA_ESUS", "OCULTAR_CODIGO_DE_BARRAS", "ODONTOGRAMA", "ORGAO_EXPEDIDOR_ALVARA_ID", "PAGINACAO_REQUISICOES_ESTOQUE", "PAINEL_SENHA", "PERMITE_LANCAMENTO_INFORMATIVO_BPA", "POSSUI_ACOLHIMENTO", "POSSUI_PRONTUARIO", "PROCEDIMENTO_OBRIGATORIO_AGENDA", "PRONTUARIO_DIGITALIZADO", "QUANTIDADE_SALAS", "RAZAO_SOCIAL", "REGISTRO_DIRETOR_CLINICO", "REMOCAO_HORARIO_RETROATIVO", "REQUISICAO_TRANSFERENCIA_AREA_ABRANGENCIA", "REQUISICAO_TRANSFERENCIA_GRUPO_SEGMENTO", "RETENCAO_TRIBUTARIA_ID", "SALVA_FICHAS_ESUS_AUTOMATICAMENTE", "SITUACAO_UNIDADE_SAUDE_ID", "STATUS", "STATUS_AVALIACAO_PNASS", "STATUS_CONTRATO_SUS", "STATUS_INTERNO", "TELEFONE", "TEMPO_CHAMADA", "TIPO_AGENDAMENTO_ID", "TIPO_ATESTADO_ID", "TIPO_AVALIACAO", "TIPO_CLASSE_AVALIACAO", "TIPO_ESFERA_ID", "TIPO_LOGRADOURO_ID", "TIPO_NATUREZA_JURIDICA_ID", "TIPO_NATUREZA_ORGANIZACAO_ID", "TIPO_PESSOA_CNES_ID", "TIPO_PRESTADOR_ID", "TIPO_RECEITUARIO_ID", "TIPO_SEPARACAO_REQUISICAO_CONSUMO_ID", "TIPO_TERCEIRO_SIH", "TIPO_UNIDADE_ID", "TIPO_UNIESP", "TIPO_VALIDACAO_AGENDAMENTO_ID", "TIPO_VALIDACAO_TRIAGEM", "TIPO_VINCULO_SUS", "TOKEN_PAINEL_SENHA", "TURNO_ATENDIMENTO_ID", "ULTIMA_ATUALIZACAO", "UNIDADE_SAUDE_ID", "UNIFICACAO_CONSULTA_PRONTUARIO", "UNIFICA_FICHA_ATENDIMENTO", "UPDATED_AT", "URGENCIA", "URL", "USUARIO_ATUALIZACAO_COORDENADAS", "USUARIO_ULTIMA_ATUALIZACAO", "UUID", "VALIDACAO_CAMPO_AFERICAO", "VALIDACAO_MUNICIPE", "VERIFICA_FILA_ESPERA_AGENDAMENTO", "VISUALIZAR_LISTA_AUSENTES_POR_CBO", "TIMESTAMP_ORIGIN", "FILENAME_ORIGIN", "Base tipo"}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Colunas Reordenadas1",{"ID", "BAIRRO", "CEP", "CLASSIFICACAO_CNES_ID", "NOME", "Tipo de Unidade", "CLIENT_NAME", "CLASSIFICACAO_RISCO_ESCUTA_INICIAL", "CODIGO_CNES", "CREATED_AT", "EMERGENCIA", "ESTADO_ID", "EXPORTACAO_ESUS", "LANCAMENTO_BPA_AUTOMATICO", "LOGRADOURO", "MUNICIPIO_ID", "NUMERO", "SITUACAO_UNIDADE_SAUDE_ID", "STATUS", "TIPO_UNIDADE_ID", "UPDATED_AT", "UNIDADE_SAUDE_ID", "UUID", "TIMESTAMP_ORIGIN", "FILENAME_ORIGIN"})
				in
				    #"Outras Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

