table SS_D_CID
	lineageTag: a66e29d0-8676-4f27-8363-384263262e75

	column ID
		dataType: string
		lineageTag: 5d2b8849-5f9f-42ad-924c-25aa1df3688a
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column CID_ID
		dataType: int64
		formatString: 0
		lineageTag: 34dd9baa-6e7a-4da1-a301-0c358cdda130
		summarizeBy: none
		sourceColumn: CID_ID

		annotation SummarizationSetBy = User

	column CODIGO
		dataType: string
		lineageTag: 4ebf5a32-3e0c-40d1-a6f0-2e218e392eaa
		summarizeBy: none
		sourceColumn: CODIGO

		annotation SummarizationSetBy = Automatic

	column NOME
		dataType: string
		lineageTag: 61edf8a6-d62b-4538-9045-86d9c1540f34
		summarizeBy: none
		sourceColumn: NOME

		annotation SummarizationSetBy = Automatic

	column CLIENT_NAME
		dataType: string
		lineageTag: db7572f3-af86-412c-9660-9706639d5663
		summarizeBy: none
		sourceColumn: CLIENT_NAME

		annotation SummarizationSetBy = Automatic

	column TIMESTAMP_ORIGIN
		dataType: string
		lineageTag: 9fe9913d-80c5-490f-840b-501d789e689c
		summarizeBy: none
		sourceColumn: TIMESTAMP_ORIGIN

		annotation SummarizationSetBy = Automatic

	column FILENAME_ORIGIN
		dataType: string
		lineageTag: 2f929888-2cb9-42c8-bc38-3c1b8d2067ac
		summarizeBy: none
		sourceColumn: FILENAME_ORIGIN

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: 05b47516-bddd-4a3e-9972-255518474b5b
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	partition SS_D_CID = m
		mode: import
		source =
				let
				  Origem = PostgreSQL.Database("om30-dl.d4all.com.br:55113", "postgres"),
				    dlv_saude_prd_ss_d_cid = Origem{[Schema="dlv_saude_prd",Item="ss_d_cid"]}[Data],
				    #"Texto em Maiúscula" = Table.TransformColumns(dlv_saude_prd_ss_d_cid,{{"NOME", Text.Upper, type text}})
				in
				    #"Texto em Maiúscula"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

