table ss_f_atendimentos
	lineageTag: f8e540cd-a811-4ae4-93fc-0aaf40bdcd4e

	measure CT_f_Atendimentos = ```
			
			CALCULATE(
			    DISTINCTCOUNT(ss_f_atendimentos[ID])
			    
			)
			```
		formatString: #,0
		lineageTag: 02023cb6-2d1f-4af4-abc4-8a2abd259bd9

	measure CT_Atendimentos_com_CIDS =
			CALCULATE(
			    DISTINCTCOUNT(ss_f_atendimentos[ATENDIMENTO_ID]),
			    FILTER(
			        ss_f_atendimentos,
			        (NOT(ISBLANK(ss_f_atendimentos[CID1_ID])) && ss_f_atendimentos[CID1_ID] <> "")
			        || (NOT(ISBLANK(ss_f_atendimentos[CID2_ID])) && ss_f_atendimentos[CID2_ID] <> "")
			    )
			)
		formatString: #,0
		lineageTag: 9e97432c-228f-4b0d-be65-16886dab9fe3

	measure CT_Atendimentos_Com_CIAP =
			COUNTROWS(
			    FILTER(
			        VALUES(ss_f_atendimentos[ID]),
			        CALCULATE(COUNTROWS(ss_b_atendimento_ciap)) > 0
			    )
			)
		formatString: #,0
		lineageTag: 24447b97-c32d-4514-9013-a0346547fa6c

	measure CT_Atendimentos_Com_CID_e_CIAP =
			VAR tComCIAP = VALUES(ss_b_atendimento_ciap[ATENDIMENTO_ID])
			VAR tAtendComCIAP =
			    CALCULATETABLE(
			        VALUES(ss_f_atendimentos[ID]),
			        TREATAS(tComCIAP, ss_f_atendimentos[ID])
			    )
			VAR tResult =
			    CALCULATETABLE(
			        VALUES(ss_f_atendimentos[ID]),
			        TREATAS(tAtendComCIAP, ss_f_atendimentos[ID]),
			        NOT(ISBLANK(ss_f_atendimentos[CID1_ID])) || NOT(ISBLANK(ss_f_atendimentos[CID2_ID]))
			    )
			RETURN COUNTROWS(tResult)
		formatString: #,0
		lineageTag: 12328366-a3b8-46d0-a91b-0e4131459b71

	measure CT_Atendimentos_Sem_CID_e_CIAP =
			VAR tTodosIDs = VALUES(ss_f_atendimentos[ID])
			VAR tComCIAP = VALUES(ss_b_atendimento_ciap[ATENDIMENTO_ID])
			VAR tSemCIAP = EXCEPT(tTodosIDs, tComCIAP)
			VAR tResult =
			    CALCULATETABLE(
			        VALUES(ss_f_atendimentos[ID]),
			        TREATAS(tSemCIAP, ss_f_atendimentos[ID]),
			        ISBLANK(ss_f_atendimentos[CID1_ID]),
			        ISBLANK(ss_f_atendimentos[CID2_ID])
			    )
			RETURN COUNTROWS(tResult)
		formatString: #,0
		lineageTag: 61f047db-ddc9-45bb-b100-9f408bbc64b8

	measure CT_f_Municipes = DISTINCTCOUNT('ss_f_atendimentos'[MUNICIPE_ID])
		formatString: #,0
		lineageTag: bc0f1be6-b076-422b-8985-a384489425d9

	measure CT_Atendimentos_por_CIAP =
			CALCULATE(
			    [CT_f_Atendimentos],
			    KEEPFILTERS(ss_b_atendimento_ciap[CIAP_ID] <> "")
			)
		formatString: #,0
		lineageTag: 30f840a3-4da9-46d8-a3cb-f4be2411cfcd

	measure CT_Atendimentos_por_CID =
			
			VAR porCID1 =
			    CALCULATE(
			        COUNTROWS(ss_f_atendimentos),
			        NOT(ISBLANK(ss_f_atendimentos[CID1_ID]))
			    )
			
			VAR porCID2 =
			    CALCULATE(
			        COUNTROWS(ss_f_atendimentos),
			        TREATAS(
			            VALUES(SS_D_CID[ID]),
			            ss_f_atendimentos[CID2_ID]
			        ),
			        NOT(ISBLANK(ss_f_atendimentos[CID2_ID]))
			    )
			
			RETURN
			    porCID1 + porCID2
		formatString: #,0
		lineageTag: 881e9a5c-c685-4c58-8088-30054d1394be

	measure CT_Municipes_por_CID =
			
			VAR porCID1 =
			    CALCULATE(
			        DISTINCTCOUNT(ss_f_atendimentos[MUNICIPE_ID]),
			        NOT ISBLANK(ss_f_atendimentos[CID1_ID])
			    )
			
			VAR porCID2 =
			    CALCULATE(
			        DISTINCTCOUNT(ss_f_atendimentos[MUNICIPE_ID]),
			        TREATAS(
			            VALUES(SS_D_CID[ID]),
			            ss_f_atendimentos[CID2_ID]
			        ),
			        NOT ISBLANK(ss_f_atendimentos[CID2_ID])
			    )
			
			RETURN
			    porCID1 + porCID2
		formatString: #,0
		lineageTag: 363fafc4-9777-4361-ad25-87fe248ed93a

	measure CT_Municipes_por_CIAP =
			CALCULATE(
			    DISTINCTCOUNT(ss_f_atendimentos[MUNICIPE_ID]),
			    FILTER(
			        VALUES(ss_f_atendimentos[ID]),
			        CALCULATE(COUNTROWS(ss_b_atendimento_ciap)) > 0
			    )
			)
		formatString: #,0
		lineageTag: 849c24cc-16cb-4af0-9b3a-ba32486c7d87

	column ID
		dataType: string
		lineageTag: 429f8605-68ab-4032-abc1-25fdbd03bd51
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column AGENDA_ID
		dataType: int64
		formatString: 0
		lineageTag: c715a0b2-4736-4279-8855-5061fd7a1acf
		summarizeBy: count
		sourceColumn: AGENDA_ID

		annotation SummarizationSetBy = Automatic

	column ATENDIMENTO_ID
		dataType: int64
		formatString: 0
		lineageTag: 2b68b6cf-568f-44ed-a71f-30c9fe5cea5f
		summarizeBy: count
		sourceColumn: ATENDIMENTO_ID

		annotation SummarizationSetBy = Automatic

	column AVALIACAO
		dataType: string
		lineageTag: 25568bba-90ac-436e-a5ff-e8c9d8dea7bc
		summarizeBy: none
		sourceColumn: AVALIACAO

		annotation SummarizationSetBy = Automatic

	column CANCELADO
		dataType: string
		lineageTag: bed3fcab-a7b0-47c8-975f-0d638044a6aa
		summarizeBy: none
		sourceColumn: CANCELADO

		annotation SummarizationSetBy = Automatic

	column CID1_ID
		dataType: string
		lineageTag: c29c89bb-9f4d-406e-a20e-4bac979e0cc7
		summarizeBy: none
		sourceColumn: CID1_ID

		annotation SummarizationSetBy = Automatic

	column CID2_ID
		dataType: string
		lineageTag: de34247f-1583-41ce-9c62-3aefbab6c513
		summarizeBy: none
		sourceColumn: CID2_ID

		annotation SummarizationSetBy = Automatic

	column CLIENT_NAME
		dataType: string
		lineageTag: e7259948-d564-40fe-bc86-79f4a97ea397
		summarizeBy: none
		sourceColumn: CLIENT_NAME

		annotation SummarizationSetBy = Automatic

	column CONDUTA
		dataType: string
		lineageTag: 2f37cea5-4065-4336-a47e-42858a3664a2
		summarizeBy: none
		sourceColumn: CONDUTA

		annotation SummarizationSetBy = Automatic

	column DATA_AGENDAMENTO
		dataType: dateTime
		formatString: Long Date
		lineageTag: 655dbe5c-26da-4e05-8b42-30fbcd6713a8
		summarizeBy: none
		sourceColumn: DATA_AGENDAMENTO

		variation Variation
			isDefault
			relationship: 220f777e-dbac-4263-8e80-2340cfdb6a13
			defaultHierarchy: LocalDateTable_5d4d96a9-e3c6-4fa9-86bf-00810039ebad.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DATA_ATENDIMENTO
		dataType: dateTime
		formatString: Short Date
		lineageTag: a07c06ef-0f88-4cbd-9483-bc8d370814a1
		summarizeBy: none
		sourceColumn: DATA_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DATA_HORA_AGENDAMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 36cdeee8-f87a-4085-9274-4397944c50a1
		summarizeBy: none
		sourceColumn: DATA_HORA_AGENDAMENTO

		variation Variation
			isDefault
			relationship: 1ac248dd-9604-4c72-8dba-7e0eacca370e
			defaultHierarchy: LocalDateTable_7a1cb8cd-c358-4000-986d-791ce53106d6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column DATA_HORA_ATENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: 6adebfeb-a056-4257-868e-608eda6846e4
		summarizeBy: none
		sourceColumn: DATA_HORA_ATENDIMENTO

		variation Variation
			isDefault
			relationship: 0573d0eb-d4f2-40aa-9f2e-696d6c039328
			defaultHierarchy: LocalDateTable_6b58c110-696e-49b3-b48b-41424f819aa4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column ESPECIALIDADE
		dataType: string
		lineageTag: 835a809e-4da7-4356-b77e-7fd49f0fa825
		summarizeBy: none
		sourceColumn: ESPECIALIDADE

		annotation SummarizationSetBy = Automatic

	column EVOLUCAO
		dataType: string
		lineageTag: aaa66468-2746-443f-bfd4-220c62b29d4b
		summarizeBy: none
		sourceColumn: EVOLUCAO

		annotation SummarizationSetBy = Automatic

	column FIM_ATENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: e3311485-c161-4f0c-90cd-893ef4af15e6
		summarizeBy: none
		sourceColumn: FIM_ATENDIMENTO

		variation Variation
			isDefault
			relationship: 339604d9-8550-44aa-b6ed-03f1be40a853
			defaultHierarchy: LocalDateTable_e2fafd0b-e474-4f30-90dc-c3d51a87f9e5.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column HORA_AGENDAMENTO
		dataType: dateTime
		formatString: Long Time
		lineageTag: a638fbfd-3908-416d-92b2-a5d29d5bf923
		summarizeBy: none
		sourceColumn: HORA_AGENDAMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column HORA_ATENDIMENTO
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9b7c81e8-5faf-429f-9f5d-9dba7224df2e
		summarizeBy: none
		sourceColumn: HORA_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column INICIO_ATENDIMENTO
		dataType: dateTime
		formatString: General Date
		lineageTag: f2974b74-29b9-41e5-b9ac-a54e21a4c365
		summarizeBy: none
		sourceColumn: INICIO_ATENDIMENTO

		variation Variation
			isDefault
			relationship: 224bcb63-c3c5-4483-b793-8e599ae26529
			defaultHierarchy: LocalDateTable_f61aec4f-8219-495d-8408-dcfc7f8db1f7.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column MUNICIPE_ID
		dataType: string
		lineageTag: bfb3d2bb-7c7b-428d-8623-7279cf02996a
		summarizeBy: none
		sourceColumn: MUNICIPE_ID

		annotation SummarizationSetBy = Automatic

	column OBJETIVO
		dataType: string
		lineageTag: c1b16f7c-a1cc-4089-9662-4f92348ea39e
		summarizeBy: none
		sourceColumn: OBJETIVO

		annotation SummarizationSetBy = Automatic

	column ORIGEM
		dataType: string
		lineageTag: 3bccdb09-ffce-493a-8173-4df179d9aba4
		summarizeBy: none
		sourceColumn: ORIGEM

		annotation SummarizationSetBy = Automatic

	column PLANO
		dataType: string
		lineageTag: 0fd981e5-99ce-4184-ba08-2e6bfb0d12d5
		summarizeBy: none
		sourceColumn: PLANO

		annotation SummarizationSetBy = Automatic

	column PROCEDIMENTO
		dataType: string
		lineageTag: 448f51ff-0740-4d44-bcb0-5c78aeccbbd2
		summarizeBy: none
		sourceColumn: PROCEDIMENTO

		annotation SummarizationSetBy = Automatic

	column PROCEDIMENTO_CODIGO
		dataType: int64
		formatString: 0
		lineageTag: b29ff4a2-a84c-4abe-bcf5-fdf04fe615d6
		summarizeBy: sum
		sourceColumn: PROCEDIMENTO_CODIGO

		annotation SummarizationSetBy = Automatic

	column PROFISSIONAL
		dataType: string
		lineageTag: fb0fec49-b5a0-4bd7-8971-076bc564abfa
		summarizeBy: none
		sourceColumn: PROFISSIONAL

		annotation SummarizationSetBy = Automatic

	column PRONTUARIO_ID
		dataType: int64
		formatString: 0
		lineageTag: 1793ec64-070c-4f99-a6f4-3e04c6b273a7
		summarizeBy: count
		sourceColumn: PRONTUARIO_ID

		annotation SummarizationSetBy = Automatic

	column PRONTUARIO_STEP
		dataType: string
		lineageTag: 925f592a-fa4b-4f01-b0fa-de6fbf28b6b4
		summarizeBy: none
		sourceColumn: PRONTUARIO_STEP

		annotation SummarizationSetBy = Automatic

	column PRONTUARIO_TIPO
		dataType: string
		lineageTag: 66670764-d993-49ff-823d-958d27e54905
		summarizeBy: none
		sourceColumn: PRONTUARIO_TIPO

		annotation SummarizationSetBy = Automatic

	column QTD_TRANSCRICOES
		dataType: int64
		formatString: 0
		lineageTag: 3927866e-ba3c-4e3c-b998-8d547c21c9fd
		summarizeBy: sum
		sourceColumn: QTD_TRANSCRICOES

		annotation SummarizationSetBy = Automatic

	column SITUACAO_PRESENCA_ATENDIMENTO
		dataType: string
		lineageTag: 817d323b-397d-41e8-a398-890dcb6dddfc
		summarizeBy: none
		sourceColumn: SITUACAO_PRESENCA_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column SUBJETIVO
		dataType: string
		lineageTag: d23cb1b6-1f5e-4b75-bf2d-66c3a1f9a046
		summarizeBy: none
		sourceColumn: SUBJETIVO

		annotation SummarizationSetBy = Automatic

	column TEM_TRANSCRICAO
		dataType: string
		lineageTag: ebb29cba-9781-4660-b9cb-fd8f9ca79186
		summarizeBy: none
		sourceColumn: TEM_TRANSCRICAO

		annotation SummarizationSetBy = Automatic

	column TIPO_ATENDIMENTO
		dataType: string
		lineageTag: e26751a5-72fd-4e5a-b52a-2955a064ecff
		summarizeBy: none
		sourceColumn: TIPO_ATENDIMENTO

		annotation SummarizationSetBy = Automatic

	column TIPO_ATIVIDADE_AGD_ID
		dataType: int64
		formatString: 0
		lineageTag: a919e5fd-796c-4292-81a0-d83bda088a8a
		summarizeBy: count
		sourceColumn: TIPO_ATIVIDADE_AGD_ID

		annotation SummarizationSetBy = Automatic

	column UNIDADE_SAUDE
		dataType: string
		lineageTag: 480a8b76-a3cf-4411-a511-b71d4c3a4d5d
		summarizeBy: none
		sourceColumn: UNIDADE_SAUDE

		annotation SummarizationSetBy = Automatic

	column UNIDADE_SAUDE_REFERENCIA_ID
		dataType: string
		lineageTag: 8b909ac9-6e2d-483a-82dc-0786d0188a14
		summarizeBy: none
		sourceColumn: UNIDADE_SAUDE_REFERENCIA_ID

		annotation SummarizationSetBy = Automatic

	column TIMESTAMP_ORIGIN
		dataType: string
		lineageTag: e6bc9723-665f-4c4c-bd1c-e6cf472a8080
		summarizeBy: none
		sourceColumn: TIMESTAMP_ORIGIN

		annotation SummarizationSetBy = Automatic

	column FILENAME_ORIGIN
		dataType: string
		lineageTag: 550997b7-9abc-4a82-8402-2db1e3be3b1c
		summarizeBy: none
		sourceColumn: FILENAME_ORIGIN

		annotation SummarizationSetBy = Automatic

	column UUID
		dataType: string
		lineageTag: b81c9e10-abe2-4219-92ac-7bed27b7e305
		summarizeBy: none
		sourceColumn: UUID

		annotation SummarizationSetBy = Automatic

	column _CID_ID
		dataType: string
		lineageTag: 79aa48a6-8dc0-418f-b7e3-fc58eafe028a
		summarizeBy: none
		sourceColumn: _CID_ID

		annotation SummarizationSetBy = Automatic

	column Unidade_saude_id = ss_f_atendimentos[UUID]&"_"&
		lineageTag: c4334af6-f677-4452-9023-d198fcbe4eac
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition ss_f_atendimentos = m
		mode: import
		source =
				let
				  Origem = PostgreSQL.Database("om30-dl.d4all.com.br:55113", "postgres"),
				    dlv_saude_prd_ss_f_atendimentos = Origem{[Schema="dlv_saude_prd",Item="ss_f_atendimentos"]}[Data],
				    #"Texto Inserido Entre os Delimitadores" = Table.AddColumn(dlv_saude_prd_ss_f_atendimentos, "_CID_ID", each Text.BetweenDelimiters([ID], "_", "_"), type text),
				    #"Linhas Classificadas" = Table.Sort(#"Texto Inserido Entre os Delimitadores",{{"MUNICIPE_ID", Order.Descending}})
				in
				    #"Linhas Classificadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Exception

